# ==========================
# Server Configuration
# ==========================
server.port=${PORT:8080}

# ==========================
# MySQL Configuration
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/online_food_order}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vaibhaovk}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vaibhao}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# Hibernate Configuration
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# ==========================
# JSP View Resolver
# ==========================
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

# ==========================
# File Upload
# ==========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
